server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: server-person
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:mysql://119.29.75.134:3306/learn
    username: vens
    password: lzq520WW
    driver-class-name: com.mysql.jdbc.Driver
  jooq:
    sql-dialect: mysql
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
flyway:
  locations: classpath:/db
