server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://119.29.75.134:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: server-person
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:mysql://119.29.75.134:3306/learn
    username: vens
    password: lzq520WW
    driver-class-name: com.mysql.jdbc.Driver
  jooq:
    sql-dialect: mysql
  rabbitmq:
    host: 119.29.75.134
    port: 5672
    username: admin
    password: 123456
    publisher-confirms: true
    publisher-returns: true
    template:
        mandatory: true
flyway:
  locations: classpath:/db
logging:
  config: classpath:log4j2.xml
